# Exercise 1: Data cleaning

Before doing actual data analysis, we usually first need to clean the data.
This might involve steps such as dealing with missing values and encoding categorical variables as integers.
In this exercise, you will perform such steps based on the Titanic passenger data.

1. Load the Titanic data set in `titanic.csv` located in the `data/` folder.
2. Report the number of observations with missing `Age`, for example using
   [`isna()`](https://pandas.pydata.org/docs/reference/api/pandas.isna.html).
3. Compute the average age in the data set. Use the following approaches and compare your results:
    1.  Use pandas's
        [`mean()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.mean.html)
        method.

        *Hint:* Select the `Age` column first, then call its `mean()` method.

    2.  Convert the `Age` column to a NumPy array using
        [`to_numpy()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html).
        Experiment with NumPy's
        [`np.mean()`](https://numpy.org/doc/stable/reference/generated/numpy.mean.html)
        and
        [`np.nanmean()`](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html)
        to see if you obtain the same results.
4. Replace all missing ages with the mean age you computed above, rounded to the nearest integer.
   You can either identify the missing values using a boolean mask and assign the mean
   age to those entries, or use
   [`fillna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html).

   Convert this updated `Age` column to integer type using
   [`astype()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.astype.html).

   *Hint:* Use `astype(int)`.

5. Generate a new column `Female` which takes on the value one if `Sex` is equal
   to `"female"` and zero if `Sex` is equal to `"male"`.
   This is called an _indicator_ or _dummy_ variable, and is useful for numerical
   analysis or regression.
   Delete the original column `Sex`.

   *Hint:* Create a new column using `df['new_column'] = values`, replacing
   `new_column` with the desired column name and `values` with the data to store.

6. Save your cleaned data set as `titanic-clean.csv` using
   [`to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html)
   with `,` as the field separator.
   Tell `to_csv()` to *not* write the `DataFrame` index to the CSV file as it's not needed in this example.

# Solution

## Part 1

In [1]:
import pandas as pd
import numpy as np

DATA_PATH = '../../data'
titanic_csv = f'{DATA_PATH}/titanic.csv'

df_titanic = pd.read_csv(titanic_csv)
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q

## Part 2

In [2]:
df_titanic['Age'].value_counts(dropna=False)

Age
NaN      177
24.00     30
22.00     27
18.00     26
28.00     25
        ...
24.50      1
0.67       1
0.42       1
34.50      1
74.00      1
Name: count, Length: 89, dtype: int64

In [3]:
df_titanic['Age'].isna().sum()

np.int64(177)

## Part 3

### Part 3.1

In [4]:
mean_age = df_titanic['Age'].mean()

### Part 3.2

In [5]:
Age_column = df_titanic['Age'].to_numpy()
np.mean(Age_column)

np.float64(nan)

In [6]:
np.nanmean(Age_column)

np.float64(29.69911764705882)

## Part 4

In [7]:
mask = df_titanic['Age'].isna()
df_titanic.loc[mask,'Age'] = mean_age

df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.000000,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.000000,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,29.699118,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,370376,7.7500,NaN,Q

In [8]:
import pandas as pd
import numpy as np

DATA_PATH = '../../data'
titanic_csv = f'{DATA_PATH}/titanic.csv'

df_titanic = pd.read_csv(titanic_csv)
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q

In [9]:
# Fill missing ages, assign to Age column
df_titanic['Age'] = df_titanic['Age'].fillna(mean_age)
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.000000,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss Margaret Edith",female,19.000000,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,29.699118,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,370376,7.7500,NaN,Q

In [10]:
df_titanic['Age'].isna().sum()

np.int64(0)

In [11]:
# Convert the Age column to an integer
df_titanic['Age'] = df_titanic['Age'].astype(int)

In [12]:
df_titanic['Age']

0      22
1      38
2      26
3      35
4      35
       ..
886    27
887    19
888    29
889    26
890    32
Name: Age, Length: 891, dtype: int64

## Part 5

In [13]:
df_titanic['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [14]:
# Create an indicator variable Female
female = df_titanic['Sex'] == 'female'
female = female.astype(int)
df_titanic['Female'] = female

# Delete the sex column
del df_titanic['Sex']
# df_titanic = df_titanic.drop(columns=['Sex'])

In [15]:
df_titanic

,PassengerId,Survived,Pclass,Name,Age,Ticket,Fare,Cabin,Embarked,Female
0,1,0,3,"Braund, Mr. Owen Harris",22,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss Laina",26,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",35,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27,211536,13.0000,NaN,S,0
887,888,1,1,"Graham, Miss Margaret Edith",19,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",29,W./C. 6607,23.4500,NaN,S,1
889,890,1,1,"Behr, Mr. Karl Howell",26,111369,30.0000,C148,C,0
890,891,0,3,"Dooley, Mr. Patrick",32,370376,7.7500,NaN,Q,0

In [16]:
df_titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Age          891 non-null    int64
 5   Ticket       891 non-null    str
 6   Fare         891 non-null    float64
 7   Cabin        204 non-null    str
 8   Embarked     889 non-null    str
 9   Female       891 non-null    int64
dtypes: float64(1), int64(5), str(4)
memory usage: 69.7 KB

In [17]:
df_titanic.to_csv(f'{DATA_PATH}/titanic-clean.csv')

df_titanic.to_excel(f'{DATA_PATH}/titanic-clean.xlsx')

***
# Exercise 2: Selecting subsets of data

In this exercise, you are asked to select subsets of macroeconomic data for the United States based on some criteria.

1.  Load the annual data from FRED which are located in `FRED_annual.xlsx`
    in the `data/FRED` folder.

    Print the list of columns and the number of non-missing observations.

    Since we are dealing with time series data, set the column `Year` as the `DataFrame`
    index.

2.  Print all observations for the 1960s decade using at least two different methods.

3.  Using the data in the column `GDP`, compute the annual GDP growth in percent
    and store it in the column `GDP_growth`. Select the years in which

    1.  GDP growth was above 5%.
    2.  GDP growth was negative, but inflation was still above 5% (such episodes are called "stagflation" since usually negative GDP growth is associated with low inflation).

        Use at least two methods for the stagflation selection.

    *Hint:* You can compute changes relative to the previous observation using the
    [`pct_change()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html)
    method.

# Part 1

In [18]:
import pandas as pd
import numpy as np

file = f'{DATA_PATH}/FRED/FRED_annual.xlsx'
df = pd.read_excel(file)
df

    Year      GDP    CPI  UNRATE  FEDFUNDS  INFLATION
0   1954   2877.7   26.9     5.6       1.0        NaN
1   1955   3083.0   26.8     4.4       1.8  -0.371747
2   1956   3148.8   27.2     4.1       2.7   1.492537
3   1957   3215.1   28.1     4.3       3.1   3.308824
4   1958   3191.2   28.9     6.8       1.6   2.846975
..   ...      ...    ...     ...       ...        ...
67  2021  21532.4  271.0     5.4       0.1   4.673619
68  2022  22075.9  292.6     3.6       1.7   7.970480
69  2023  22723.7  304.7     3.6       5.0   4.135338
70  2024  23358.4  313.7     4.0       5.1   2.953725
71  2025  23850.4  322.0     4.3       4.2   2.645840

[72 rows x 6 columns]

In [19]:
print(df.columns)
print(df.notna().sum())

Index(['Year', 'GDP', 'CPI', 'UNRATE', 'FEDFUNDS', 'INFLATION'], dtype='str')
Year         72
GDP          72
CPI          72
UNRATE       72
FEDFUNDS     72
INFLATION    71
dtype: int64

In [20]:
df.set_index('Year',inplace=True)

In [21]:
df

          GDP    CPI  UNRATE  FEDFUNDS  INFLATION
Year
1954   2877.7   26.9     5.6       1.0        NaN
1955   3083.0   26.8     4.4       1.8  -0.371747
1956   3148.8   27.2     4.1       2.7   1.492537
1957   3215.1   28.1     4.3       3.1   3.308824
1958   3191.2   28.9     6.8       1.6   2.846975
...       ...    ...     ...       ...        ...
2021  21532.4  271.0     5.4       0.1   4.673619
2022  22075.9  292.6     3.6       1.7   7.970480
2023  22723.7  304.7     3.6       5.0   4.135338
2024  23358.4  313.7     4.0       5.1   2.953725
2025  23850.4  322.0     4.3       4.2   2.645840

[72 rows x 5 columns]

# Part 2

In [22]:
print(df.loc[1960:1969])
print(df.iloc[6:16])

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION
Year
1960  3500.3  29.6     5.5       3.2   1.369863
1961  3590.1  29.9     6.7       2.0   1.013514
1962  3810.1  30.3     5.6       2.7   1.337793
1963  3976.1  30.6     5.6       3.2   0.990099
1964  4205.3  31.0     5.2       3.5   1.307190
1965  4478.6  31.5     4.5       4.1   1.612903
1966  4773.9  32.5     3.8       5.1   3.174603
1967  4904.9  33.4     3.8       4.2   2.769231
1968  5145.9  34.8     3.6       5.7   4.191617
1969  5306.6  36.7     3.5       8.2   5.459770
         GDP   CPI  UNRATE  FEDFUNDS  INFLATION
Year
1960  3500.3  29.6     5.5       3.2   1.369863
1961  3590.1  29.9     6.7       2.0   1.013514
1962  3810.1  30.3     5.6       2.7   1.337793
1963  3976.1  30.6     5.6       3.2   0.990099
1964  4205.3  31.0     5.2       3.5   1.307190
1965  4478.6  31.5     4.5       4.1   1.612903
1966  4773.9  32.5     3.8       5.1   3.174603
1967  4904.9  33.4     3.8       4.2   2.769231
1968  5145.9  34.8     3.6       5.7   4.191617
1969  5306.6  36.7     3.5       8.2   5.459770

# Part 3

## Part 3.1

In [23]:
GDP_growth = df['GDP'].pct_change() * 100
df['GDP_growth'] = GDP_growth
df[df['GDP_growth'] > 5]

          GDP    CPI  UNRATE  FEDFUNDS  INFLATION  GDP_growth
Year
1955   3083.0   26.8     4.4       1.8  -0.371747    7.134170
1959   3412.4   29.2     5.4       3.3   1.038062    6.931562
1962   3810.1   30.3     5.6       2.7   1.337793    6.127963
1964   4205.3   31.0     5.2       3.5   1.307190    5.764443
1965   4478.6   31.5     4.5       4.1   1.612903    6.498942
1966   4773.9   32.5     3.8       5.1   3.174603    6.593578
1972   5780.0   41.8     5.6       4.4   3.209877    5.255490
1973   6106.4   44.4     4.9       8.7   6.220096    5.647059
1976   6387.4   56.9     7.7       5.0   5.762082    5.386989
1978   7052.7   65.2     6.1       7.9   7.590759    5.535105
1984   8195.3  103.9     7.5      10.2   4.317269    7.236042
2021  21532.4  271.0     5.4       0.1   4.673619    6.151988

## Part 3.2

In [24]:
df[(df['GDP_growth'] < 0) & (df['INFLATION'] > 5)]

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION  GDP_growth
Year
1974  6073.4  49.3     5.6      10.5  11.036036   -0.540417
1975  6060.9  53.8     8.5       5.8   9.127789   -0.205816
1980  7257.3  82.4     7.2      13.4  13.498623   -0.257009
1982  7307.3  96.5     9.7      12.3   6.160616   -1.803400

In [25]:
df.query('GDP_growth < 0 & INFLATION > 5')

         GDP   CPI  UNRATE  FEDFUNDS  INFLATION  GDP_growth
Year
1974  6073.4  49.3     5.6      10.5  11.036036   -0.540417
1975  6060.9  53.8     8.5       5.8   9.127789   -0.205816
1980  7257.3  82.4     7.2      13.4  13.498623   -0.257009
1982  7307.3  96.5     9.7      12.3   6.160616   -1.803400

***
# Exercise 3: Labor market statistics for the US

In this exercise, you are asked to compute some descriptive statistics for the
unemployment rate and the labor force participation rate for the United States.
The latter is the percentage of the civilian noninstitutional population aged 16
and older who are in the labor force (employed or unemployed). Both rates are
expressed as percentages.

1.  Load the monthly time series from FRED which are located in `FRED_monthly.csv`
    in the `data/FRED` folder.

    *Hint:* Use `pd.read_csv(..., parse_dates=['DATE'])` to automatically
    parse strings stored in the `DATE` column as dates.

    Since we are dealing with time series data, set the column `DATE` as the
    `DataFrame` index. Then print the list of columns and the number of non-missing
    observations.

2.  For the columns `UNRATE` (unemployment rate) and `LFPART` (labor force
    participation rate), compute and report
    the mean, minimum, and maximum values for the whole sample. Round your results
    to one decimal place.

    *Hint:* You can use the `DataFrame` methods
    [`mean()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.mean.html),
    [`min()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.min.html), and
    [`max()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.max.html)
    to compute the desired statistics.

    *Hint:* You can use the `DataFrame` method
    [`round()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.round.html)
    to round the results to one decimal place.

3.  You are interested in how the average unemployment rate evolved over the last
    few decades.

    -   Add a new column `Decade` to the `DataFrame` which contains the
        starting year for each decade (e.g., this value should be 1950
        for the years 1950-1959, and so on).

        *Hint:* The decade can be computed from the column `Year` using
        truncated integer division:
        ```python
        df['Year'] // 10 * 10
        ```

    -   Write a loop to compute and report the average unemployment rate
        (column `UNRATE`) for each decade.

        Include only the decades from 1950 to 2010 for which you have all
        observations.

# Part 1

In [26]:
file = f'{DATA_PATH}/FRED/FRED_monthly.csv'
df = pd.read_csv(file, parse_dates=['DATE'])
df = df.set_index('DATE')

In [27]:
print(df.columns)
df.notna().sum()

Index(['Year', 'Month', 'CPI', 'UNRATE', 'FEDFUNDS', 'REALRATE', 'LFPART'], dtype='str')

Year        936
Month       936
CPI         935
UNRATE      935
FEDFUNDS    858
REALRATE    528
LFPART      935
dtype: int64

# Part 2

In [28]:
unrate_mean = df['UNRATE'].mean().round(1)
unrate_min = df['UNRATE'].min().round(1)
unrate_max = df['UNRATE'].max().round(1)
print(f'The mean of unemployment rate is {unrate_mean},\n'
      f'the minimum of unemployment rate is {unrate_min},\n'
      f'the maximum of unemployment rate is {unrate_max}')

lfpart_mean = df['LFPART'].mean().round(1)
lfpart_min = df['LFPART'].min().round(1)
lfpart_max = df['LFPART'].max().round(1)
print(f'The mean of labour force participation rate is {lfpart_mean},\n'
      f'the minimum of labour force participation rate is {lfpart_min},\n'
      f'the maximum of labour force participation rate is {lfpart_max}')

The mean of unemployment rate is 5.7,
the minimum of unemployment rate is 2.5,
the maximum of unemployment rate is 14.8
The mean of labour force participation rate is 62.8,
the minimum of labour force participation rate is 58.1,
the maximum of labour force participation rate is 67.3

In [29]:
df[['UNRATE', 'LFPART']].agg(['mean', 'min', 'max']).round(1)

      UNRATE  LFPART
mean     5.7    62.8
min      2.5    58.1
max     14.8    67.3

# Part 3

In [30]:
decades = df['Year'] // 10 * 10
df['Decade'] = decades
df

            Year  Month    CPI  UNRATE  FEDFUNDS  REALRATE  LFPART  Decade
DATE
1948-01-01  1948      1   23.7     3.4       NaN       NaN    58.6    1940
1948-02-01  1948      2   23.7     3.8       NaN       NaN    58.9    1940
1948-03-01  1948      3   23.5     4.0       NaN       NaN    58.5    1940
1948-04-01  1948      4   23.8     3.9       NaN       NaN    59.0    1940
1948-05-01  1948      5   24.0     3.5       NaN       NaN    58.3    1940
...          ...    ...    ...     ...       ...       ...     ...     ...
2025-08-01  2025      8  323.3     4.3       4.3       1.5    62.3    2020
2025-09-01  2025      9  324.2     4.4       4.2       1.1    62.5    2020
2025-10-01  2025     10    NaN     NaN       4.1       1.0     NaN    2020
2025-11-01  2025     11  325.1     4.5       3.9       1.0    62.5    2020
2025-12-01  2025     12  326.0     4.4       3.7      -0.1    62.4    2020

[936 rows x 8 columns]

In [31]:
years = range(1950, 2020, 10)

for decade in years:
    mask = df['Decade'] == decade
    df_decade = df[mask]
    unrate_mean = df_decade['UNRATE'].mean().round(1)
    print(f'The average unemployment rate in {decade}s is {unrate_mean}')

The average unemployment rate in 1950s is 4.5
The average unemployment rate in 1960s is 4.8
The average unemployment rate in 1970s is 6.2
The average unemployment rate in 1980s is 7.3
The average unemployment rate in 1990s is 5.8
The average unemployment rate in 2000s is 5.5
The average unemployment rate in 2010s is 6.2

***
# Exercise 4: Daily stock-market returns

In this exercise, you will compute daily returns for the S&P 500 index and count
trading days with losses or large gains. The column `SP500` contains the index
values.

1.  Load `SP500.csv` from the `data/stockmarket` folder, parse `Date` as dates, and
    set it as the `DataFrame` index. Restrict the data to observations after
    January 1, 2020.

    *Hint:* Use `pd.read_csv(..., parse_dates=['Date'])` to automatically parse the
    strings in the `Date` column as dates.

2.  Compute daily returns in percent using
    [`pct_change()`](
    https://pandas.pydata.org/docs/reference/api/pandas.Series.pct_change.html
    )
    and store them in a new column `Return`. Explain why the first return is
    missing.

    *Hint:* Multiply the result of `pct_change()` by 100 to express returns in
    percent.

3.  Report the number and percentage of trading days with losses, i.e., negative
    returns. Exclude days with missing returns from the denominator.

    *Hint:* Summing a Boolean `Series` counts the number of `True` values. Use
    [`count()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.count.html)
    to count nonmissing observations.

4.  Report the number and percentage of trading days with gains of more than 5%.
5.  Report the number and percentage of days with negative returns on both the
    current and the previous trading day. A run of three loss days contributes
    two qualifying days. For the percentage, include only days with both returns
    observed.

    *Hint:* Use
    [`shift()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.shift.html)
    to obtain the previous trading day's return, and combine the two conditions
    using `&`.

# Part 1

In [32]:
file = f'{DATA_PATH}/stockmarket/SP500.csv'
df = pd.read_csv(file, parse_dates=['Date'])
df = df.set_index('Date')
df

             SP500
Date
1950-01-03    16.7
1950-01-04    16.9
1950-01-05    16.9
1950-01-06    17.0
1950-01-09    17.1
...            ...
2025-12-23  6909.8
2025-12-24  6932.0
2025-12-26  6929.9
2025-12-29  6905.7
2025-12-30  6896.2

[19120 rows x 1 columns]

In [33]:
df = df.loc["2020-01-01":]
df

             SP500
Date
2020-01-02  3257.9
2020-01-03  3234.9
2020-01-06  3246.3
2020-01-07  3237.2
2020-01-08  3253.1
...            ...
2025-12-23  6909.8
2025-12-24  6932.0
2025-12-26  6929.9
2025-12-29  6905.7
2025-12-30  6896.2

[1507 rows x 1 columns]

# Part 2

In [34]:
df['Return'] = df['SP500'].pct_change() * 100
df

             SP500    Return
Date
2020-01-02  3257.9       NaN
2020-01-03  3234.9 -0.705976
2020-01-06  3246.3  0.352407
2020-01-07  3237.2 -0.280319
2020-01-08  3253.1  0.491165
...            ...       ...
2025-12-23  6909.8  0.455041
2025-12-24  6932.0  0.321283
2025-12-26  6929.9 -0.030294
2025-12-29  6905.7 -0.349211
2025-12-30  6896.2 -0.137568

[1507 rows x 2 columns]

# Part 3

In [35]:
days = df['Return'].count()
mask = df['Return'] < 0
days_negative = mask.sum()
pct_days_negative = round(days_negative / days * 100, 2)

print(f'There are {days} days in total. {days_negative} days are losing, which is {pct_days_negative}%')

There are 1506 days in total. 685 days are losing, which is 45.48%

# Part 4

In [36]:
mask_lar5 = df['Return'] > 5
lar5 = mask_lar5.sum()
pct_lar5 = round(lar5 / days * 100 , 2)

print(f'There are {lar5} days with return larger than 5%, which is {pct_lar5}%')

There are 7 days with return larger than 5%, which is 0.46%

In [37]:
df[mask_lar5]

             SP500    Return
Date
2020-03-13  2711.0  9.288075
2020-03-17  2529.2  5.997234
2020-03-24  2447.3  9.381425
2020-03-26  2630.1  6.240911
2020-04-06  2663.7  7.036085
2022-11-10  3956.4  5.543403
2025-04-09  5456.9  9.514731

# Part 5

In [49]:
days

np.int64(1505)

In [48]:
df_previous_day = df['Return'].shift()
count_df = df['Return'].notna()
count_dfp = df_previous_day.notna()
days = (count_df & count_dfp).sum()

mask1 = df['Return'] < 0
mask2 = df['Return'].shift() < 0
mask_candy = mask1 & mask2

candy = mask_candy.sum()
pct_candy = round(candy / days * 100, 2)

print(f'There are {candy} days with return negative in both the current day and the previous day, which is {pct_candy}%')

There are 296 days with return negative in both the current day and the previous day, which is 19.67%

***
# Exercise 5: Working with string data (advanced)

Most of the data we deal with contain strings, i.e., text data (names, addresses, etc.). Often, such data is not in the format needed for analysis, and we have to perform additional string manipulation to extract the exact data we need. This can be achieved using the pandas
[string methods](https://pandas.pydata.org/docs/user_guide/text.html#string-methods).

To illustrate, we use the Titanic data set for this exercise.

1.  Load the Titanic data and restrict the sample to men. (This simplifies the task. Some
    married women's entries contain both their husband's name and their maiden name.)
2.  Print the first five observations of the `Name` column. As you can see, the data is stored in the format _"Last name, Title First name"_ where the title is something like Mr., Rev., etc.
3.  Split the `Name` column by `,` to extract the last name and the remainder as separate columns. You can achieve this using the
   [`partition()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.partition.html)
   string method.
4. Split the remainder (containing the title and first name) using the space
   character `" "` as separator to obtain individual columns for the title and
   the first name.

   *Hint:* The remainder starts with a space after the comma. Use `.str.strip()`
   to remove leading and trailing whitespace before splitting it.

5. Store the three data series in the original `DataFrame` (using the column names `FirstName`, `LastName`, and `Title`) and delete the `Name` column, which is no longer needed.
6. Finally, extract the ship deck from the values in `Cabin`. The ship deck is the first character in the string stored in `Cabin` (A, B, C, ...). You extract the first character using the
   [`get()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.get.html)
   string method. Store the result in the column `Deck`.

*Hint*: pandas's string methods can be accessed using the `.str` attribute. For example,
to partition values in the column `Name`, you need to use
```python
df['Name'].str.partition()
```